function newStorageTest()
%Page creation
f = figure ('Name','Monitoring Window','NumberTitle','off')


%Tab creation
tabgp = uitabgroup('parent',f,...
    'Position',[.01 .20 0.98 .75]);
drawnow;
tabMonitoringFlex1 = uitab(tabgp, 'Title', 'Box1');
tabMonitoringFlex2 = uitab(tabgp, 'Title', 'Box2');
tabMonitoringFlex3 = uitab(tabgp, 'Title', 'Box3');
tabMonitoringFlex4 = uitab(tabgp, 'Title', 'Box4');

%%%%%%%%%%%%%%%
%BOX1
%Table creation
columnNames = {'Variable','Value','Time stamp',...
    'Variable Stage 1','Value Stage 1','Time stamp Stage 1',...
    'Variable Stage 2','Value Stage 2','Time stamp Stage 2',...
    'Variable Stage 3','Value Stage 3','Time stamp Stage 3',...
    'Variable Stage 4','Value Stage 4','Time stamp Stage 4'};
t = uitable('parent',tabMonitoringFlex1, 'ColumnWidth',{150}, ...
    'Position',[10 5 530 230],...
    'ColumnName',columnNames,...
    'Tag', 't',...
    'visible','off');


%Table's button
buVarsBox1 = uicontrol('parent',tabMonitoringFlex1,...
    'Style','pushbutton',...
    'Position',[10 240 80 35],...
    'String', 'See Variables',... 
    'Callback',{@buVarsBox1_Callback,t});

%Performance's button
buPerformBox1 = uicontrol('Style','pushButton',...
    'parent',tabMonitoringFlex1,...
    'Backgroundcolor',[0.94 0.94 0.94],...
    'Position',[120 240 150 35],...
    'visible', 'on', ...
    'String','See Performance Graph');

%Lateralization's button
buLateralizeBox1 = uicontrol('Style','pushButton',...
    'parent',tabMonitoringFlex1,...
    'Backgroundcolor',[0.94 0.94 0.94],...
    'Position',[300 240 150 35],...
    'visible', 'on', ...
    'String','See Lateralization Graph',...
    'Callback',@callLum);

%Plot all's button
buPlotAllBox1 = uicontrol('Style','pushButton',...
    'parent',f,...
    'Backgroundcolor',[0.94 0.94 0.94],...
    'Position',[10 10 150 35],...
    'visible', 'on', ...
    'String','Plot all performances');

%Pause button
buPauseBox1 = uicontrol('Style','pushButton',...
    'parent',f,...
    'Backgroundcolor',[0.94 0.94 0.94],...
    'Position',[310 10 110 35],...
    'visible', 'on', ...
    'String','Pause experiment');

%Stop button
buPauseBox1 = uicontrol('Style','pushButton',...
    'parent',f,...
    'Backgroundcolor',[0.94 0.94 0.94],...
    'Position',[440 10 110 35],...
    'visible', 'on', ...
    'String','Stop experiment');

lateralizeAxes1 = axes('parent',tabMonitoringFlex1,...
         'Position',[0.1,0.1,0.7,0.7]);
 x = 0:0.1:100;
 y = 3*x;
 plot (lateralizeAxis1,x,y,'+');

%test(t)
%drawnow;
%m = test(t) %POUR RECUPERER LES DONNEES
%drawnow;
%m=luminance(t)
drawnow;

%Push button callback function (see tabs)
function buVarsBox1_Callback(hObject, callbackdata, t)
set(t,'visible','on');

%Push button callback function(see lateralization)
function callLum(src,event)
%plot
axis on
% [pos, dirPos] = luminance () % AU LIEU DE RELANCER LUMINANCE(), CHERCHER LES DONNEES DANS LA MATRICE
% plot(lateralizePlot1,pos,dirPos,'+');
 x = 0:0.1:100;
 y = 3*x;
 plot (lateralizeAxis1,x,y,'+');
%switch to plot tab
set (tabgp,'SelectedTab',tabMonitoringFlex1);
drawnow



% %passage en .csv
% function exportCSV(Passation)
% csvfile=[Passation.Filename '.csv'];
% fprintf('Exporting data to: %s\n', csvfile);
% [t,h]=Data2tab(Passation.Data);
% fid =fopen(csvfile, 'wt');
% fprintf(fid,'%s,', h{:});
% fprintf(fid,'\n');
% fclose(fid);
% dlmwrite(csvfile,t, '-append', 'delimiter', ',');
% 
% function [t,h]=Data2tab(Data)
% h={'Trial' 'Block' 'Reversal' 'Trial/Block' 'Trial/Pair' ...
%     'StimLeft' 'StimRight' 'TargetSide' 'Response' 'RT' 'Accuracy' ...
%     'Confidence level' 'Confidence RT' ...
%     'Prob.Error' 'Feedback'};
% t=[ ...
%     Data.i_trial(:) ...
%     Data.i_rev(:) ...
%     Data.newblock(:) ...
%     Data.i_trial_per_rev(:) ...
%     Data.i_trial_per_stims(:) ...
%     Data.stims ...
%     Data.side(:) ...
%     Data.resp(:) ...
%     Data.rt(:)*1000 ...
%     Data.accu(:) ...
%     Data.resp_conf(:) ...
%     Data.rt_conf(:)*1000 ...
%     Data.prob_error(:) ...
%     Data.fb(:)...
%     ];
